# fly.toml file generated for loanpro-api2 on 2022-11-14T15:45:00-09:00

app = "loanpro-api"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  SECRET = "fd4s5a64fd654a6ds54te564tr6e5g46fd5a4fd6a46sd54f6sda"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = false
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "30s"
    restart_limit = 0
    timeout = "10s"
